### ISSUE TITLE
Change the default port or add the ability to change it

### ISSUE THREAD

**Issue by THPubs** [thinkholic/wordpress-cli#43]
I just tried to run the tool and it tried to run on port 8888. Unfortunately, I have `resilio-sync` running on that port. Is there a way to change the port? (It worked after turning off the service.). Better if we can have it run on port 3000 like meteor 😄 

Let me know what you think. I can help :-)

**Comment by kasunben** [comment]
@THPubs 
It's one of the first task is going to fix in the next version. :).
Related issue #15

**Comment by THPubs** [comment]
Perfect :smile:
